site_name: Runnable Snippets
nav:
  - Home: index.md
  - Tools, Tips, Tricks:
    - Playground links.md
    - Scaffold with CLI.md
    - Packages.md
    - Installation hints.md
    - Cross.md
    - Android.md
  - Concurrency:
    - Async.md
    - Channels.md
    - Share.md
  - Constructs:
    - For Enumerate.md
    - For Range.md
  - Data types:
    - DateTime.md
    - Dict.md
    - Globals.md
    - List.md
    - String.md
    - Structure or Class.md
    - Tuples.md
    - Union.md
  - Execution time.md
  - FFI:
    - C Callable.md
    - C Call.md
  - File:
    - Write & Read lines.md
    - CSV.md
    - Serialization.md
    - TOML.md
  - Frameworks:
    - Flutter.md
  - GUI:
    - Fltk.md
    - GTK.md
  - Science:
    - Charts.md
    - Numeric.md
    - Excel Read.md
  - System command.md
  - Video:
    - VideoCapture.md
    - FaceDetect.md

theme:
  name: 'material'
  palette:
    primary: 'lime'
    accent: 'lime'
  #feature:
  #  - tabs
  icon:
    logo: material/database
  favicon: images/database.svg
markdown_extensions:
  - codehilite:
      guess_lang: false    
#extra:
#   version: 2.0
dev_addr: '127.0.0.1:8081'
