site_name: Runnable Snippets
nav:
  - Home: index.md
  - Tools, Tips, Tricks:
    - Playground links.md
    - Scaffold with CLI.md
    - Packages.md
    - Installation hints.md
    - Cross.md
    - Android.md
  - Concurrency:
    - Async.md
    - Channels.md
    - Share.md
  - Constructs:
    - For Enumerate.md
    - For Range.md
  - Data types:
    - DateTime.md
    - Dict.md
    - Conversions.md
    - Globals.md
    - List.md
    - String.md
    - Structure or Class.md
    - Tuples.md
    - Union.md
  - Execution time.md
  - FFI:
    - C Callable.md
    - C Call.md
  - File:
    - Write & Read lines.md
    - CSV.md
    - JSON.md
    - Serialization.md
    - TOML.md
    - File Walk.md
  - Frameworks:
    - Flutter.md
  - GUI:
    - Fltk.md
    - Fyne.md
    - GTK.md
  - Net:
    - Webserver.md
    - Websockets.md
  - Science:
    - Charts.md
    - Dataframe.md
    - Numeric.md
    - Excel Read.md
  - System command.md
  - Video:
    - VideoCapture.md
    - FaceDetect.md

theme:
  #name: terminal
  #name: dracula
  name: material
  palette:
    primary: 'lime'
    accent: 'lime'
  #feature:
  #  - tabs
  icon:
    logo: material/database
  favicon: images/database.svg
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/dart.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/julia.min.js
  - https://unpkg.com/highlightjs-copy/dist/highlightjs-copy.min.js
  - https://unpkg.com/highlightjs-copy/dist/highlightjs-copy.min.css
  - add_hljs_highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/a11y-light.min.css
#markdown_extensions:
#  - codehilite:
#      guess_lang: false
#extra:
#   version: 2.0
dev_addr: '127.0.0.1:8081'
