site_name: Snippets
nav:
  - Home: index.md
  - Dictionary: dictionary.md
  - Hello: hello.md
theme:
  name: 'material'
  palette:
    primary: 'lime'
    accent: 'lime'
markdown_extensions:
  - codehilite:
      guess_lang: false    
    