site_name: Snippets
nav:
  - Home: index.md
  - Playground Links: playglinks.md
  - Dictionary: dictionary.md
  - Hello with CLI: hello.md
  - Lists: lists1.md
#  - Lists:
#    - New List w and w/o value: lists1.md
  - System command: syscom.md
theme:
  name: 'material'
  palette:
    primary: 'lime'
    accent: 'lime'
  #feature:
  #  tabs: true
  logo:
    icon: 'language'
  favicon: 
  #  icon: 'language'
markdown_extensions:
  - codehilite:
      guess_lang: false    
extra:
   version: 2.0
    