site_name: Runnable Snippets
nav:
  - Home: index.md
  - Tools:
    - Playground links.md
    - Installation tricks.md
    - Packages.md
  - Concurrency:
    - Async.md
    - Channels.md
  - Constructs:
    - For Enumerate.md
    - For Range.md
  - Cross.md
  - Data types:
    - Dict.md
    - List.md
    - String.md
    - Structure or Class.md
    - Union.md
  - Execution time.md
  - FFI:
    - C Callable.md
    - C Call.md
  - File:
    - Write & Read lines.md
  - Frameworks:
    - Flutter.md
  - GUI:
    - GTK.md
  - Numeric.md
  - Scaffold with CLI.md
  - System command.md
theme:
  name: 'material'
  palette:
    primary: 'lime'
    accent: 'lime'
  #feature:
  #  tabs: true
  logo:
    icon: 'language'
  favicon: 
  #  icon: 'language'
markdown_extensions:
  - codehilite:
      guess_lang: false    
extra:
   version: 2.0
    