site_name: Snippets
nav:
  - Home: index.md
  - Playground links.md
  - Data types:
    - Dict.md
    - List.md
  - Execution time.md
  - File:
    - Write & Read lines.md
  - Scaffold with CLI.md
  - System command.md
theme:
  name: 'material'
  palette:
    primary: 'lime'
    accent: 'lime'
  #feature:
  #  tabs: true
  logo:
    icon: 'language'
  favicon: 
  #  icon: 'language'
markdown_extensions:
  - codehilite:
      guess_lang: false    
extra:
   version: 2.0
    